function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 14-Feb-2023 15:34:07

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 2;        % Order
    % F0   = 0.5;      % Center frequency
    % BW   = 0.3;      % Bandwidth
    % Gref = -10;      % Reference gain
    % G0   = 0;        % Center frequency gain
    % GBW  = -3.0103;  % Bandwidth gain
    %
    % h = fdesign.parameq('N,F0,BW,Gref,G0,GBW', N, F0, BW, Gref, G0, GBW);
    %
    % Hd = design(h, 'butter', ...
    %     'FilterStructure', 'df1sos', ...
    %     'SOSScaleNorm', 'Linf', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form I', ...
        'SOSMatrix', [0.530290212330875 0 -0.0958318665580685 1 0 ...
        0.373877921111056], ...
        'ScaleValues', [1; 1]);
end

s = single(x);
y = step(Hd,s);

